sudo: false

env:
 - GHCVER=7.8.4 STACK_YAML=stack-ghc-7.8.4.yaml
 - GHCVER=7.10.3 STACK_YAML=stack.yaml

cache:
  directories:
    - $HOME/.stack/

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.0.2/stack-1.0.2-linux-x86_64.tar.gz | tar -xvz
 - mv stack-1.0.2-linux-x86_64/stack ~/.local/bin
 - export PATH=~/.local/bin:$PATH
 - stack --version

install:
 - stack install --only-dependencies --no-terminal

script:
 - stack test :regression --coverage --no-terminal

after_script:
 - stack install stack-hpc-coveralls
 - shc ether regression

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.8.4
    - ghc-7.10.3