sudo: false

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.1.2/stack-1.1.2-linux-x86_64.tar.gz | tar -xvz
  - mv stack-1.1.2-linux-x86_64/stack ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - stack --version
  - stack setup

install:
 - stack install --only-dependencies --no-terminal

script:
 - stack test ether-suite:regression --no-terminal --ghc-options -Werror
 - stack bench ether-suite:bench --no-terminal --ghc-options -Werror

addons:
  apt:
    packages:
    - libgmp-dev
